<a href="https://colab.research.google.com/github/kotrying/ML_Theory/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 1階テンソル - ベクトル
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
# 2階テンソル - 行列
np.array([[1,2,3],
          [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 3階テンソル
np.array([[[1,2,3],
           [2,3,4]],
          [[2,3,4],
           [5,6,7]]])

array([[[1, 2, 3],
        [2, 3, 4]],

       [[2, 3, 4],
        [5, 6, 7]]])

In [ ]:
# テンソルの次元を変更する
tensor1 = np.arange(24)
print('ベクトル\n', tensor1)
print('ベクトルの形状\n', tensor1.shape)
# 1階テンソルから3階テンソルへ
tensor3 = tensor1.reshape(2,3,4)
print('3階テンソル\n', tensor3)
print('3階テンソルの形状\n', tensor3.shape)

ベクトル
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
ベクトルの形状
 (24,)
3階テンソル
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3階テンソルの形状
 (2, 3, 4)


In [ ]:
# 3階テンソルから4階テンソルへ
tensor4 = tensor3.reshape(2,2,3,2)
print('4階テンソル\n', tensor4)
print('4階テンソルの形状\n', tensor4.shape)

4階テンソル
 [[[[ 0  1]
   [ 2  3]
   [ 4  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]
   [16 17]]

  [[18 19]
   [20 21]
   [22 23]]]]
4階テンソルの形状
 (2, 2, 3, 2)


In [ ]:
# 要素数が異なる場合はエラー
tensor3.reshape(2,2,2,5)

ValueError: ignored

In [ ]:
# テンソルの軸を変更する
tensor4 = np.arange(48).reshape(2,2,3,4)
print('4階テンソル\n', tensor4)
print('4階テンソルの形状\n', tensor4.shape)
# axis (0,1,2,3) -> (1,2,3,0)
tensor4t = tensor4.transpose(1,2,3,0)
print('軸変更4階テンソル\n', tensor4t)
print('軸変更4階テンソルの形状\n', tensor4t.shape)

4階テンソル
 [[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]

  [[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]
4階テンソルの形状
 (2, 2, 3, 4)
軸変更4階テンソル
 [[[[ 0 24]
   [ 1 25]
   [ 2 26]
   [ 3 27]]

  [[ 4 28]
   [ 5 29]
   [ 6 30]
   [ 7 31]]

  [[ 8 32]
   [ 9 33]
   [10 34]
   [11 35]]]


 [[[12 36]
   [13 37]
   [14 38]
   [15 39]]

  [[16 40]
   [17 41]
   [18 42]
   [19 43]]

  [[20 44]
   [21 45]
   [22 46]
   [23 47]]]]
軸変更4階テンソルの形状
 (2, 3, 4, 2)
